### ISSUE TITLE
Set up jena endpoint with tailscale

### ISSUE THREAD

**Issue by tomlue** [biobricks-ai/biobricks-okg#20]
- [x] TL - update tailscale
- [x] ZM - set up jena on ws2
- [x] ZM - get ws2 publicly visible

**Comment by zmughal** [comment]
Closed by <https://github.com/biobricks-ai/biobricks-okg/pull/25> and <https://github.com/biobricks-ai/biobricks-okg/commit/2a4326d098ba95cbcb018c52a30aa9c786f9b0e4>.
