### ISSUE TITLE
fix the deprecates outs in dvc.lock files when they don't have a match in dvc.yaml files for each repo

### ISSUE THREAD

**Issue by tomlue** [biobricks-ai/biobricks-okg#27]

**Comment by zmughal** [comment]
- <https://github.com/biobricks-ai/biogrid/pull/1>
- <https://github.com/biobricks-ai/chebirdf/pull/2>
- <https://github.com/biobricks-ai/rtecs/pull/1>
- <https://github.com/biobricks-ai/cpcat/pull/1>
- <https://github.com/biobricks-ai/toxvaldb/pull/1>
- <https://github.com/biobricks-ai/cancerharmony/pull/1>
- <https://github.com/biobricks-ai/cpdat/pull/1>
- <https://github.com/biobricks-ai/dbgap/pull/1>
- <https://github.com/biobricks-ai/pdb/pull/2>
- <https://github.com/biobricks-ai/chembl/pull/6>
- <https://github.com/biobricks-ai/toxcast/pull/2>
- <https://github.com/biobricks-ai/moleculenet/pull/1>
- <https://github.com/biobricks-ai/chebi/pull/1>
- <https://github.com/biobricks-ai/zinc/pull/1>
- <https://github.com/biobricks-ai/uniprot-kg/pull/1>
- <https://github.com/biobricks-ai/USPTO_ChemReaction/pull/1>
- <https://github.com/biobricks-ai/openfda/pull/1>
- <https://github.com/biobricks-ai/mesh-kg/pull/1>
- <https://github.com/biobricks-ai/geneontology/pull/2>

**Comment by zmughal** [comment]
This is done. The above change to `brick-template` would be useful to prevent the cause of most of the old stages.
